### ISSUE TITLE
Feature request: Add [img][/img] BBCode tags and add support for copying image thumbnail links

### ISSUE THREAD

**Issue by zotoro** [BC44/Release-Info-Creator#1]
Can you add the option to add [img][/img] BBCode tags and give users the option to choose between copying urls to the direct image vs copying urls to the image thumbnails? Imgbb supports image thumbnails and some trackers require thumbnails instead of links to the full-size image.

**Comment by BC44** [comment]
I could add [img] tags, but they'd also need to be hyperlinked in order for people to be able to check out the full-sized image if they want.

thumb url: https://i.ibb.co/bzTC42h/0-snapshot-2021-02-21-15-49-55.png
full sized url: https://i.ibb.co/BqbQhrD/0-snapshot-2021-02-21-15-49-55.png

So in that case, the bbcode-formatted image could go like this

`[url=https://i.ibb.co/BqbQhrD/0-snapshot-2021-02-21-15-49-55.png][img]https://i.ibb.co/bzTC42h/0-snapshot-2021-02-21-15-49-55.png[/img][/url]`

Would you say that's fine?

Also consider the medium-sized thumbnail: https://i.ibb.co/D5hvB8X/0-snapshot-2021-02-21-15-49-55.png (in contrast to the small-sized thumb that I used above).

**Comment by zotoro** [comment]
Yea, I think being able to choose either thumbnail size would be a nice quality of life addition. The BBCode in your example looks correct.

Adding the [img] tags is the big one, since as far as I know every tracker supports the tags while not every tracker will show images without the tags.

**Comment by BC44** [comment]
Added in aae7e11aae02e2001f0c0a994033ddc03dbc0bda
