### ISSUE TITLE
Shared seedbox error

### ISSUE THREAD

**Issue by kevzz1284** [BC44/Release-Info-Creator#2]
Hello,

I managed to install all those modules but getting this error :

keev@123:~/data/scripts$ python ReleaseInfoCreator.py "/home/keev/data/123123123.mkv"
Traceback (most recent call last):
  File "ReleaseInfoCreator.py", line 10, in <module>
    from Settings import Settings
  File "/home/keev/data/scripts/Settings.py", line 58
    print(f'\nExisting settings file not found, a new one will be created '
                                                                          ^
SyntaxError: invalid syntax
 
Any idea why?

P.S - I do not have root access

**Comment by BC44** [comment]
What version of python do you have installed? Try running `python3 --version`

**Comment by kevzz1284** [comment]
Hi @BC44 

python3 --version
Python 3.4.2

I believe it's outdated?

**Comment by BC44** [comment]
Yes, 3.6 was required, though the version number was unnecessarily high. I've lowered the python version req in 6fe3b211dc8b11bc5d443a2096d1f68975cbfad1

Update and you should be able to use it without issues.

**Comment by kevzz1284** [comment]
> Yes, 3.6 was required, though the version number was unnecessarily high. I've lowered the python version req in [6fe3b21](https://github.com/BC44/Release-Info-Creator/commit/6fe3b211dc8b11bc5d443a2096d1f68975cbfad1)
> 
> Update and you should be able to use it without issues.

thanks for the prompt reply but it's still not working.. I just checked and seems like only Settings.py got changed, but i replaced all the files and still getting this error -

Traceback (most recent call last):
  File "ReleaseInfoCreator.py", line 10, in <module>
    from Settings import Settings
  File "/home/keev/data/scripts/Settings.py", line 113
    Settings.image_hosts[i]['api_key'] = input(f'\nInput the API key for {host_name} (to skip, leave blank): ')
                                                                                                             ^
SyntaxError: invalid syntax

But note now that line number changed.. last time i got this :

File "/home/keev/data/scripts/Settings.py", line 58

and now :

File "/home/keev/data/scripts/Settings.py", line 113

here is a diff checker - https://www.diffchecker.com/vQSq7Snr just to double confirm the code..

**Comment by kevzz1284** [comment]
Just a quick question.. do i need to edit the setting file and input my APi, username details etc before running the script?

**Comment by BC44** [comment]
I've reverted the changes I made. It seems Pillow requires python 3.6 for the newer versions. Unfortunately you will have to install python 3.6 somehow to use this script.



> Just a quick question.. do i need to edit the setting file and input my APi, username details etc before running the script?

The script asks for that info on first run, if the settings file does not exist.

**Comment by kevzz1284** [comment]
> I've reverted the changes I made. It seems Pillow requires python 3.6 for the newer versions. Unfortunately you will have to install python 3.6 somehow to use this script.
> 
> > Just a quick question.. do i need to edit the setting file and input my APi, username details etc before running the script?
> 
> The script asks for that info on first run, if the settings file does not exist.

thanks for looking into this. I got a reply from the seedbox provider -

"The version is what distro provides."

So they are not going to upgrade this for me. So no other way i can make it work, right?

**Comment by BC44** [comment]
You can try installing miniconda (https://docs.conda.io/en/latest/miniconda.html#linux-installers), which is another python interpreter. You can install it without root.

Run: 

```
wget "download_url" -O miniconda.sh
bash miniconda.sh
```

After it installs, run `conda activate` to enter conda's python virtual environment, then you can run my script as normal

**Comment by kevzz1284** [comment]
> You can try installing miniconda (https://docs.conda.io/en/latest/miniconda.html#linux-installers), which is another python interpreter. You can install it without root.
> 
> Run:
> 
> ```
> wget "download_url" -O miniconda.sh
> bash miniconda.sh
> ```
> 
> After it installs, run `conda activate` to enter conda's python virtual environment, then you can run my script as normal

Thanks so much, it's working great now :)

**Comment by BC44** [comment]
Glad to hear it :)
